name: lapakita
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.1
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  glassmorphism: ^3.0.0
  http: ^0.13.5
  url_launcher: ^6.1.5
  json_annotation: ^4.6.0
  flutter_native_splash: ^2.2.8
  carousel_slider: ^4.1.1
  image_picker: ^0.8.5+3
  persistent_bottom_nav_bar: ^4.0.2

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0
  equatable: ^2.0.5

  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
